### ISSUE TITLE
Add/clarify that os.environ return dictionary of all vars

### ISSUE THREAD

**Issue by lantzbuilds** [Matt-Eva/using-environment-variables-in-flask#1]
I love everything about this.  I might just add a sentence to 'Using os.environ' which notes that `os.environ` alone returns a dictionary of all accessible environment variables.  If you wanted to elucidate, you could add a code snippet which would iterate over all the key/val pairs, something like:
`for key, value in os.environ.items():`
 `     print(key, value)`

**Comment by Matt-Eva** [comment]
Great idea, @betalantz ! Just added some language about that. If you have any more edits / suggestions, please keep em coming! Feel free to just make a PR too if you'd like.
